name: open_card_game
description: A card game but cheaper.
# version: 1.0.0
#homepage: https://www.imperialoctopus.com/
#author: Zoey Child <imperialoctopus@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  js: ^0.6.0
  angular: ^6.0.0-alpha
  angular_router: ^2.0.0-alpha+22
  angular_forms: ^2.1.0
  pdf: ^1.3.18
  image: ^2.1.4
  csv: ^4.0.3

dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers:
  pedantic: ^1.9.0
